# Required GitHub Secrets for Remote Server Access:
# - REMOTE_VM_HOST: Remote server hostname/IP
# - REMOTE_VM_USER: Remote server SSH username
# - REMOTE_SSH_KEY: SSH private key for remote server access

name: Deploy Container

on:
  workflow_dispatch:

env:
  CONTAINER_NAME: msj-revision-api
  IMAGE_NAME: msj-revision-api
  REGISTRY_URL: ghcr.io
  IMAGE_TAG: latest
  HOST_PORT: 8080
  CONTAINER_PORT: 8080
  APP_NAME: "msj-revision-api"
  APP_VERSION: "1.0.0"
  APP_PORT: "8080"
  APP_URL: "/api/v1"
  OLLAMA_CHAT_API: "https://ollama.srvd.dev/api/chat"
  LL_MODEL: "deepseek-r1:14b"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          # Deploy container using SSH with key from secret
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.REMOTE_SSH_KEY }}") "${{ secrets.REMOTE_VM_USER }}@${{ secrets.REMOTE_VM_HOST }}" "\
            docker rm -f ${{ env.CONTAINER_NAME }} || true && \
            docker pull ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} && \
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} \
              -e APP_NAME="${{ env.APP_NAME }}" \
              -e APP_VERSION="${{ env.APP_VERSION }}" \
              -e APP_PORT="${{ env.APP_PORT }}" \
              -e APP_URL="${{ env.APP_URL }}" \
              -e OLLAMA_CHAT_API="${{ env.OLLAMA_CHAT_API }}" \
              -e LL_MODEL="${{ env.LL_MODEL }}" \
              ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
