# Required GitHub Secrets:
# - GH_ACCESS_TOKEN: GitHub access token for container registry and workflow dispatch
#

name: Build and Push Container Image

on:
  push:
    branches:
      - main # Trigger on main branch push, modify as needed

env:
  CONTAINER_NAME: msj-revision-api
  IMAGE_NAME: msj-revision-api
  REGISTRY_URL: ghcr.io
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push to registry
        run: docker push ${{ env.REGISTRY_URL }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Trigger deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          token: ${{ secrets.GH_ACCESS_TOKEN }}
