name: Docker Image CI

on:
  push:
    branches: [main]

env:
  CONTAINER_NAME: msj-revision-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to GITHUB Docker Registry
        run: docker login --username ${{ secrets.GH_ACCESS_TOKEN }} --password ${{ secrets.GH_ACCESS_TOKEN }} ghcr.io
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/rturnbull/$CONTAINER_NAME:latest
      - name: Push the latest Docker image
        run: docker push ghcr.io/rturnbull/$CONTAINER_NAME:latest
        
